function simulateur_circuit_RLC()
% =========================================================================
% SIMULATEUR DE CIRCUITS RC / RLC
% Interface graphique MATLAB pour tester et stimuler des circuits RC et RLC
% Signaux supportes : Impulsion Dirac, Peigne Dirac, Echelon Unite,
%                     Rampe, Sinus 50 Hz
% =========================================================================

clc; close all;

%% --- Creation de la figure principale ---
fig = figure('Name', 'Simulateur RC / RLC', ...
    'NumberTitle', 'off', ...
    'Position', [50 50 1400 820], ...
    'Color', [0.12 0.14 0.18], ...
    'Resize', 'on', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none');

%% =========================================================================
%  PANNEAU GAUCHE : Parametres
%% =========================================================================
pLeft = uipanel(fig, ...
    'Position', [0.01 0.01 0.27 0.98], ...
    'BackgroundColor', [0.16 0.18 0.24], ...
    'ForegroundColor', [0.55 0.85 1.0], ...
    'Title', '  PARAMETRES', ...
    'FontName', 'Consolas', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BorderType', 'line', ...
    'HighlightColor', [0.3 0.6 0.9]);

% ---- Titre decoratif ----
uicontrol(pLeft, 'Style','text', ...
    'String', '⚡ SIMULATEUR RC / RLC ⚡', ...
    'Units','normalized', 'Position',[0.05 0.94 0.90 0.05], ...
    'FontName','Consolas','FontSize',10,'FontWeight','bold', ...
    'ForegroundColor',[0.3 0.9 0.7],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','center');

% ========== SECTION 1 : Type de circuit ==========
uicontrol(pLeft,'Style','text','String','── TYPE DE CIRCUIT ──', ...
    'Units','normalized','Position',[0.05 0.89 0.90 0.04], ...
    'FontName','Consolas','FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',[0.55 0.85 1.0],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','center');

uicontrol(pLeft,'Style','text','String','Circuit :', ...
    'Units','normalized','Position',[0.05 0.85 0.35 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');

hdl.popCircuit = uicontrol(pLeft,'Style','popupmenu', ...
    'String',{'RC (Passe-bas)','RC (Passe-haut)','RLC Serie','RLC Parallele'}, ...
    'Units','normalized','Position',[0.40 0.855 0.55 0.035], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[0.3 0.9 0.7], ...
    'Callback', @updateInterface);

% ========== SECTION 2 : Parametres du circuit ==========
uicontrol(pLeft,'Style','text','String','── COMPOSANTS ──', ...
    'Units','normalized','Position',[0.05 0.81 0.90 0.03], ...
    'FontName','Consolas','FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',[0.55 0.85 1.0],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','center');

% R
uicontrol(pLeft,'Style','text','String','R (Ω) :', ...
    'Units','normalized','Position',[0.05 0.775 0.40 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');
hdl.editR = uicontrol(pLeft,'Style','edit','String','1000', ...
    'Units','normalized','Position',[0.50 0.778 0.44 0.033], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.85 0.3]);

% C
uicontrol(pLeft,'Style','text','String','C (µF) :', ...
    'Units','normalized','Position',[0.05 0.735 0.40 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');
hdl.editC = uicontrol(pLeft,'Style','edit','String','1', ...
    'Units','normalized','Position',[0.50 0.738 0.44 0.033], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.85 0.3]);

% L
uicontrol(pLeft,'Style','text','String','L (mH) :', ...
    'Units','normalized','Position',[0.05 0.695 0.40 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');
hdl.editL = uicontrol(pLeft,'Style','edit','String','10', ...
    'Units','normalized','Position',[0.50 0.698 0.44 0.033], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.85 0.3]);
hdl.lblL = uicontrol(pLeft,'Style','text','String','(RLC uniquement)', ...
    'Units','normalized','Position',[0.05 0.668 0.90 0.025], ...
    'FontName','Consolas','FontSize',7,'FontAngle','italic', ...
    'ForegroundColor',[0.5 0.5 0.5],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','center');

% ========== SECTION 3 : Type de signal ==========
uicontrol(pLeft,'Style','text','String','── SIGNAL D''ENTREE ──', ...
    'Units','normalized','Position',[0.05 0.635 0.90 0.03], ...
    'FontName','Consolas','FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',[0.55 0.85 1.0],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','center');

uicontrol(pLeft,'Style','text','String','Signal :', ...
    'Units','normalized','Position',[0.05 0.598 0.35 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');

hdl.popSignal = uicontrol(pLeft,'Style','popupmenu', ...
    'String',{'Impulsion de Dirac','Peigne de Dirac','Echelon Unite','Rampe','Sinus 50 Hz'}, ...
    'Units','normalized','Position',[0.40 0.600 0.55 0.035], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.5 0.7], ...
    'Callback', @updateSignalParams);

% ========== SECTION 4 : Parametres du signal ==========
uicontrol(pLeft,'Style','text','String','── PARAMS SIGNAL ──', ...
    'Units','normalized','Position',[0.05 0.565 0.90 0.03], ...
    'FontName','Consolas','FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',[0.55 0.85 1.0],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','center');

% Amplitude
uicontrol(pLeft,'Style','text','String','Amplitude (V) :', ...
    'Units','normalized','Position',[0.05 0.530 0.50 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');
hdl.editAmp = uicontrol(pLeft,'Style','edit','String','1', ...
    'Units','normalized','Position',[0.56 0.533 0.38 0.033], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.85 0.3]);

% Duree
uicontrol(pLeft,'Style','text','String','Duree (ms) :', ...
    'Units','normalized','Position',[0.05 0.490 0.50 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');
hdl.editDuree = uicontrol(pLeft,'Style','edit','String','50', ...
    'Units','normalized','Position',[0.56 0.493 0.38 0.033], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.85 0.3]);

% Frequence sinus
hdl.lblFreq = uicontrol(pLeft,'Style','text','String','Frequence (Hz) :', ...
    'Units','normalized','Position',[0.05 0.450 0.50 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left','Visible','off');
hdl.editFreq = uicontrol(pLeft,'Style','edit','String','50', ...
    'Units','normalized','Position',[0.56 0.453 0.38 0.033], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.85 0.3], ...
    'Visible','off');

% Periode peigne
hdl.lblPeriode = uicontrol(pLeft,'Style','text','String','Periode peigne (ms) :', ...
    'Units','normalized','Position',[0.05 0.410 0.55 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left','Visible','off');
hdl.editPeriode = uicontrol(pLeft,'Style','edit','String','10', ...
    'Units','normalized','Position',[0.60 0.413 0.34 0.033], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.85 0.3], ...
    'Visible','off');

% Offset DC
uicontrol(pLeft,'Style','text','String','Offset DC (V) :', ...
    'Units','normalized','Position',[0.05 0.370 0.50 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');
hdl.editOffset = uicontrol(pLeft,'Style','edit','String','0', ...
    'Units','normalized','Position',[0.56 0.373 0.38 0.033], ...
    'FontName','Consolas','FontSize',9, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[1 0.85 0.3]);

% ========== SECTION 5 : Options d'affichage ==========
uicontrol(pLeft,'Style','text','String','── AFFICHAGE ──', ...
    'Units','normalized','Position',[0.05 0.335 0.90 0.03], ...
    'FontName','Consolas','FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',[0.55 0.85 1.0],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','center');

hdl.chkEntree = uicontrol(pLeft,'Style','checkbox','String',' Signal entree', ...
    'Units','normalized','Position',[0.05 0.300 0.90 0.03], ...
    'FontName','Consolas','FontSize',9,'Value',1, ...
    'ForegroundColor',[0.4 0.9 0.4],'BackgroundColor',[0.16 0.18 0.24]);

hdl.chkSortie = uicontrol(pLeft,'Style','checkbox','String',' Signal sortie (Vc)', ...
    'Units','normalized','Position',[0.05 0.268 0.90 0.03], ...
    'FontName','Consolas','FontSize',9,'Value',1, ...
    'ForegroundColor',[1 0.6 0.2],'BackgroundColor',[0.16 0.18 0.24]);

hdl.chkBode = uicontrol(pLeft,'Style','checkbox','String',' Diagramme de Bode', ...
    'Units','normalized','Position',[0.05 0.236 0.90 0.03], ...
    'FontName','Consolas','FontSize',9,'Value',1, ...
    'ForegroundColor',[0.7 0.5 1.0],'BackgroundColor',[0.16 0.18 0.24]);

% Echelle log/lin
uicontrol(pLeft,'Style','text','String','Echelle temps :', ...
    'Units','normalized','Position',[0.05 0.200 0.50 0.03], ...
    'FontName','Consolas','FontSize',9, ...
    'ForegroundColor',[0.85 0.85 0.85],'BackgroundColor',[0.16 0.18 0.24], ...
    'HorizontalAlignment','left');
hdl.popEchelle = uicontrol(pLeft,'Style','popupmenu', ...
    'String',{'Lineaire','Logarithmique'}, ...
    'Units','normalized','Position',[0.55 0.202 0.40 0.033], ...
    'FontName','Consolas','FontSize',8, ...
    'BackgroundColor',[0.22 0.26 0.34],'ForegroundColor',[0.85 0.85 0.85]);

% ========== BOUTONS ==========
hdl.btnSim = uicontrol(pLeft,'Style','pushbutton', ...
    'String','▶  SIMULER', ...
    'Units','normalized','Position',[0.05 0.145 0.90 0.048], ...
    'FontName','Consolas','FontSize',11,'FontWeight','bold', ...
    'BackgroundColor',[0.1 0.6 0.3],'ForegroundColor',[1 1 1], ...
    'Callback', @simuler);

hdl.btnReset = uicontrol(pLeft,'Style','pushbutton', ...
    'String','↺  REINITIALISER', ...
    'Units','normalized','Position',[0.05 0.090 0.90 0.040], ...
    'FontName','Consolas','FontSize',10, ...
    'BackgroundColor',[0.5 0.2 0.1],'ForegroundColor',[1 1 1], ...
    'Callback', @reinitialiser);

hdl.btnExport = uicontrol(pLeft,'Style','pushbutton', ...
    'String','💾  EXPORTER PNG', ...
    'Units','normalized','Position',[0.05 0.045 0.90 0.040], ...
    'FontName','Consolas','FontSize',10, ...
    'BackgroundColor',[0.2 0.3 0.55],'ForegroundColor',[1 1 1], ...
    'Callback', @exporterFig);

% Zone info en bas
hdl.txtInfo = uicontrol(pLeft,'Style','text', ...
    'String','Pret.', ...
    'Units','normalized','Position',[0.02 0.005 0.96 0.035], ...
    'FontName','Consolas','FontSize',8, ...
    'ForegroundColor',[0.4 0.8 0.4],'BackgroundColor',[0.10 0.12 0.16], ...
    'HorizontalAlignment','left');

%% =========================================================================
%  PANNEAU DROIT : Graphiques
%% =========================================================================
pRight = uipanel(fig, ...
    'Position', [0.295 0.01 0.70 0.98], ...
    'BackgroundColor', [0.10 0.12 0.16], ...
    'ForegroundColor', [0.55 0.85 1.0], ...
    'Title', '  VISUALISATION', ...
    'FontName', 'Consolas', ...
    'FontSize', 11, 'FontWeight','bold', ...
    'BorderType', 'line', ...
    'HighlightColor', [0.3 0.6 0.9]);

% Axe 1 : Signal entree
hdl.ax1 = axes(pRight, 'Position',[0.07 0.69 0.88 0.24], ...
    'Color',[0.06 0.08 0.12], ...
    'XColor',[0.5 0.7 0.9],'YColor',[0.5 0.7 0.9], ...
    'GridColor',[0.3 0.35 0.4],'GridAlpha',0.4, ...
    'FontName','Consolas','FontSize',8, ...
    'XGrid','on','YGrid','on','Box','on');
title(hdl.ax1,'Signal d''Entree e(t)','Color',[0.4 0.9 0.4],'FontName','Consolas','FontSize',9,'FontWeight','bold');
xlabel(hdl.ax1,'Temps (ms)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);
ylabel(hdl.ax1,'Amplitude (V)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);

% Axe 2 : Signal sortie
hdl.ax2 = axes(pRight, 'Position',[0.07 0.39 0.88 0.24], ...
    'Color',[0.06 0.08 0.12], ...
    'XColor',[0.5 0.7 0.9],'YColor',[0.5 0.7 0.9], ...
    'GridColor',[0.3 0.35 0.4],'GridAlpha',0.4, ...
    'FontName','Consolas','FontSize',8, ...
    'XGrid','on','YGrid','on','Box','on');
title(hdl.ax2,'Signal de Sortie s(t) — Tension aux bornes de C','Color',[1 0.6 0.2],'FontName','Consolas','FontSize',9,'FontWeight','bold');
xlabel(hdl.ax2,'Temps (ms)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);
ylabel(hdl.ax2,'Amplitude (V)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);

% Axe 3 : Bode
hdl.ax3 = axes(pRight, 'Position',[0.07 0.06 0.88 0.27], ...
    'Color',[0.06 0.08 0.12], ...
    'XColor',[0.5 0.7 0.9],'YColor',[0.5 0.7 0.9], ...
    'GridColor',[0.3 0.35 0.4],'GridAlpha',0.4, ...
    'FontName','Consolas','FontSize',8, ...
    'XGrid','on','YGrid','on','Box','on','XScale','log');
title(hdl.ax3,'Diagramme de Bode — |H(jω)| (dB)','Color',[0.7 0.5 1.0],'FontName','Consolas','FontSize',9,'FontWeight','bold');
xlabel(hdl.ax3,'Frequence (Hz)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);
ylabel(hdl.ax3,'Gain (dB)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);

% Texte infos circuit
hdl.txtCircuit = uicontrol(pRight,'Style','text', ...
    'String','Selectionnez un circuit et appuyez sur SIMULER', ...
    'Units','normalized','Position',[0.02 0.965 0.96 0.025], ...
    'FontName','Consolas','FontSize',8,'FontWeight','bold', ...
    'ForegroundColor',[0.3 0.9 0.7],'BackgroundColor',[0.10 0.12 0.16], ...
    'HorizontalAlignment','center');

%% Sauvegarde des handles dans la figure
guidata(fig, hdl);
updateInterface(fig, []);
updateSignalParams(fig, []);

%% =========================================================================
%  CALLBACKS
%% =========================================================================

    function updateInterface(src, ~)
        h = guidata(fig);
        idx = get(h.popCircuit,'Value');
        % Activer L seulement pour RLC
        if idx >= 3
            set(h.editL,'Enable','on','ForegroundColor',[1 0.85 0.3]);
            set(h.lblL,'ForegroundColor',[0.5 0.5 0.5]);
        else
            set(h.editL,'Enable','off','ForegroundColor',[0.4 0.4 0.4]);
        end
    end

    function updateSignalParams(src, ~)
        h = guidata(fig);
        idx = get(h.popSignal,'Value');
        % Sinus : afficher freq
        if idx == 5
            set(h.lblFreq,'Visible','on');
            set(h.editFreq,'Visible','on');
        else
            set(h.lblFreq,'Visible','off');
            set(h.editFreq,'Visible','off');
        end
        % Peigne : afficher periode
        if idx == 2
            set(h.lblPeriode,'Visible','on');
            set(h.editPeriode,'Visible','on');
        else
            set(h.lblPeriode,'Visible','off');
            set(h.editPeriode,'Visible','off');
        end
    end

    function simuler(~, ~)
        h = guidata(fig);
        set(h.txtInfo,'String','Simulation en cours...','ForegroundColor',[1 0.8 0.2]);
        drawnow;

        try
            %% Lecture des parametres
            R = str2double(get(h.editR,'String'));
            C = str2double(get(h.editC,'String')) * 1e-6;
            L = str2double(get(h.editL,'String')) * 1e-3;
            Amp = str2double(get(h.editAmp,'String'));
            Duree_ms = str2double(get(h.editDuree,'String'));
            Offset = str2double(get(h.editOffset,'String'));
            Freq = str2double(get(h.editFreq,'String'));
            Periode_peigne = str2double(get(h.editPeriode,'String')) * 1e-3;

            if any(isnan([R C L Amp Duree_ms Offset]))
                set(h.txtInfo,'String','ERREUR : Parametres invalides.','ForegroundColor',[1 0.3 0.3]);
                return;
            end

            Duree = Duree_ms * 1e-3;
            Fs = max(1e5, 1000 / Duree_ms * 1e3); % freq echantillonnage adaptative
            dt = 1/Fs;
            t = 0:dt:Duree;
            N = length(t);

            idxCircuit = get(h.popCircuit,'Value');
            idxSignal  = get(h.popSignal,'Value');

            %% Generation du signal entree
            switch idxSignal
                case 1 % Impulsion Dirac
                    e = zeros(1,N);
                    e(1) = Amp / dt; % approximation Dirac
                case 2 % Peigne de Dirac
                    e = zeros(1,N);
                    idx_imp = round(0:Periode_peigne*Fs:N-1) + 1;
                    idx_imp = idx_imp(idx_imp <= N);
                    e(idx_imp) = Amp / dt;
                case 3 % Echelon Unite
                    e = Amp * ones(1,N);
                    e(1:max(1,round(N*0.05))) = 0; % petit retard 5%
                case 4 % Rampe
                    e = Amp * t / Duree;
                case 5 % Sinus 50 Hz
                    e = Amp * sin(2*pi*Freq*t);
            end
            e = e + Offset;

            %% Construction fonction de transfert H(s)
            switch idxCircuit
                case 1 % RC Passe-bas : H(s) = 1/(1+RCs)
                    num = [1];
                    den = [R*C 1];
                    label_H = sprintf('RC Passe-bas  |  R=%gΩ  C=%gµF  |  fc=%.1f Hz', ...
                        R, C*1e6, 1/(2*pi*R*C));
                case 2 % RC Passe-haut : H(s) = RCs/(1+RCs)
                    num = [R*C 0];
                    den = [R*C 1];
                    label_H = sprintf('RC Passe-haut  |  R=%gΩ  C=%gµF  |  fc=%.1f Hz', ...
                        R, C*1e6, 1/(2*pi*R*C));
                case 3 % RLC Serie Passe-bas (sortie sur C)
                    % H(s) = (1/LC) / (s^2 + (R/L)s + 1/LC)
                    w0 = 1/sqrt(L*C);
                    Q  = (1/R)*sqrt(L/C);
                    num = [w0^2];
                    den = [1, R/L, 1/(L*C)];
                    fc  = w0/(2*pi);
                    label_H = sprintf('RLC Serie  |  R=%gΩ L=%gmH C=%gµF  |  f0=%.1f Hz  Q=%.2f', ...
                        R, L*1e3, C*1e6, fc, Q);
                case 4 % RLC Parallele Passe-bas (sortie sur C)
                    w0 = 1/sqrt(L*C);
                    Q  = R*sqrt(C/L);
                    num = [w0^2];
                    den = [1, w0/Q, w0^2];
                    fc  = w0/(2*pi);
                    label_H = sprintf('RLC Parallele  |  R=%gΩ L=%gmH C=%gµF  |  f0=%.1f Hz  Q=%.2f', ...
                        R, L*1e3, C*1e6, fc, Q);
            end

            sys = tf(num, den);

            %% Simulation reponse temporelle (lsim)
            try
                [s, t_out] = lsim(sys, e, t);
                s = s';
                t_out = t_out';
            catch ME
                set(h.txtInfo,'String',['Erreur lsim: ' ME.message],'ForegroundColor',[1 0.3 0.3]);
                return;
            end

            %% Echelle de temps
            t_ms    = t * 1e3;
            t_out_ms = t_out * 1e3;
            echelle = get(h.popEchelle,'Value');

            %% ----------- AXE 1 : Entree -----------
            cla(h.ax1);
            axes(h.ax1); %#ok
            hold(h.ax1,'on');

            if get(h.chkEntree,'Value')
                if idxSignal == 1 || idxSignal == 2
                    % Afficher stems pour les impulsions
                    stem(h.ax1, t_ms, e*dt, 'Color',[0.3 0.95 0.5], ...
                        'LineWidth',1.2,'Marker','none','BaseValue',0);
                    % Marquer les positions
                    idx_nonzero = find(e ~= 0);
                    if ~isempty(idx_nonzero)
                        stem(h.ax1, t_ms(idx_nonzero), Amp*ones(size(idx_nonzero)), ...
                            'Color',[0.3 0.95 0.5],'LineWidth',1.8,'MarkerSize',6);
                    end
                else
                    plot(h.ax1, t_ms, e, 'Color',[0.3 0.95 0.5],'LineWidth',1.5);
                end
                legend(h.ax1, 'e(t)','TextColor',[0.3 0.95 0.5], ...
                    'Color',[0.08 0.10 0.15],'EdgeColor',[0.3 0.4 0.5], ...
                    'FontName','Consolas','FontSize',8,'Location','northeast');
            end
            hold(h.ax1,'off');
            set(h.ax1,'Color',[0.06 0.08 0.12], ...
                'XColor',[0.5 0.7 0.9],'YColor',[0.5 0.7 0.9], ...
                'GridColor',[0.3 0.35 0.4],'XGrid','on','YGrid','on');
            if echelle == 2, set(h.ax1,'XScale','log'); else, set(h.ax1,'XScale','linear'); end
            title(h.ax1,'Signal d''Entree e(t)','Color',[0.4 0.9 0.4],'FontName','Consolas','FontSize',9,'FontWeight','bold');
            xlabel(h.ax1,'Temps (ms)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);
            ylabel(h.ax1,'Amplitude (V)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);

            %% ----------- AXE 2 : Sortie -----------
            cla(h.ax2);
            if get(h.chkSortie,'Value')
                plot(h.ax2, t_out_ms, s, 'Color',[1 0.6 0.2],'LineWidth',1.8);
                legend(h.ax2,'s(t) = Vc(t)','TextColor',[1 0.6 0.2], ...
                    'Color',[0.08 0.10 0.15],'EdgeColor',[0.3 0.4 0.5], ...
                    'FontName','Consolas','FontSize',8,'Location','northeast');
            end
            set(h.ax2,'Color',[0.06 0.08 0.12], ...
                'XColor',[0.5 0.7 0.9],'YColor',[0.5 0.7 0.9], ...
                'GridColor',[0.3 0.35 0.4],'XGrid','on','YGrid','on');
            if echelle == 2, set(h.ax2,'XScale','log'); else, set(h.ax2,'XScale','linear'); end
            title(h.ax2,'Signal de Sortie s(t)','Color',[1 0.6 0.2],'FontName','Consolas','FontSize',9,'FontWeight','bold');
            xlabel(h.ax2,'Temps (ms)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);
            ylabel(h.ax2,'Amplitude (V)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);

            %% ----------- AXE 3 : Bode -----------
            cla(h.ax3);
            if get(h.chkBode,'Value')
                f_bode = logspace(0, 6, 2000);
                w_bode = 2*pi*f_bode;
                [mag, phase_bode] = bode(sys, w_bode);
                mag    = squeeze(mag);
                phase_bode = squeeze(phase_bode);
                mag_dB = 20*log10(mag + eps);

                yyaxis(h.ax3,'left');
                semilogx(h.ax3, f_bode, mag_dB, 'Color',[0.7 0.5 1.0],'LineWidth',1.8);
                ylabel(h.ax3,'Gain (dB)','Color',[0.7 0.5 1.0],'FontName','Consolas','FontSize',8);
                set(h.ax3,'YColor',[0.7 0.5 1.0]);

                yyaxis(h.ax3,'right');
                semilogx(h.ax3, f_bode, phase_bode, 'Color',[0.4 0.8 0.9],'LineWidth',1.2,'LineStyle','--');
                ylabel(h.ax3,'Phase (deg)','Color',[0.4 0.8 0.9],'FontName','Consolas','FontSize',8);
                set(h.ax3,'YColor',[0.4 0.8 0.9]);

                % Ligne -3 dB
                yyaxis(h.ax3,'left');
                hold(h.ax3,'on');
                yline(h.ax3, max(mag_dB)-3, '--', 'Color',[1 0.4 0.4],'LineWidth',1, ...
                    'Label','-3 dB','LabelHorizontalAlignment','left', ...
                    'FontName','Consolas','FontSize',7);
                hold(h.ax3,'off');

                legend(h.ax3,{'|H(f)| (dB)','∠H(f) (°)'}, ...
                    'TextColor',[0.85 0.85 0.85], ...
                    'Color',[0.08 0.10 0.15],'EdgeColor',[0.3 0.4 0.5], ...
                    'FontName','Consolas','FontSize',8,'Location','southwest');
            end
            set(h.ax3,'Color',[0.06 0.08 0.12], ...
                'XColor',[0.5 0.7 0.9], ...
                'GridColor',[0.3 0.35 0.4],'XGrid','on','YGrid','on', ...
                'XScale','log');
            title(h.ax3,'Diagramme de Bode','Color',[0.7 0.5 1.0],'FontName','Consolas','FontSize',9,'FontWeight','bold');
            xlabel(h.ax3,'Frequence (Hz)','Color',[0.7 0.7 0.7],'FontName','Consolas','FontSize',8);

            %% Info circuit
            set(h.txtCircuit,'String', label_H);
            set(h.txtInfo,'String',sprintf('✓ Simulation OK  |  N=%d points  |  Fs=%.0f kHz', N, Fs/1e3), ...
                'ForegroundColor',[0.4 0.9 0.4]);

        catch ME
            set(h.txtInfo,'String',['ERREUR: ' ME.message],'ForegroundColor',[1 0.3 0.3]);
        end
    end % simuler

    function reinitialiser(~, ~)
        h = guidata(fig);
        set(h.editR,'String','1000');
        set(h.editC,'String','1');
        set(h.editL,'String','10');
        set(h.editAmp,'String','1');
        set(h.editDuree,'String','50');
        set(h.editFreq,'String','50');
        set(h.editPeriode,'String','10');
        set(h.editOffset,'String','0');
        set(h.popCircuit,'Value',1);
        set(h.popSignal,'Value',1);
        set(h.chkEntree,'Value',1);
        set(h.chkSortie,'Value',1);
        set(h.chkBode,'Value',1);
        set(h.popEchelle,'Value',1);
        cla(h.ax1); cla(h.ax2); cla(h.ax3);
        set(h.txtInfo,'String','Reinitialise.','ForegroundColor',[0.4 0.8 0.4]);
        set(h.txtCircuit,'String','Selectionnez un circuit et appuyez sur SIMULER');
        updateInterface(fig,[]);
        updateSignalParams(fig,[]);
    end

    function exporterFig(~, ~)
        h = guidata(fig);
        fname = ['simulateur_RLC_' datestr(now,'yyyymmdd_HHMMSS') '.png'];
        try
            exportgraphics(fig, fname, 'Resolution', 150);
            set(h.txtInfo,'String',['Exporte : ' fname],'ForegroundColor',[0.3 0.9 0.7]);
        catch
            saveas(fig, fname);
            set(h.txtInfo,'String',['Exporte : ' fname],'ForegroundColor',[0.3 0.9 0.7]);
        end
    end

end % fin fonction principale